export const FETCH_USERS__BEGIN = 'FETCH_USERS__BEGIN';
export const FETCH_USERS__SUCCESS = 'FETCH_USERS__SUCCESS';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const FETCH_PEOPLE_BEGIN = 'FETCH_PEOPLE_BEGIN';
export const FETCH_PEOPLE_SUCCESS = 'FETCH_PEOPLE_SUCCESS';
export const FETCH_PEOPLE_FAILURE = 'FETCH_PEOPLE_FAILURE';